
# Site settings
title: Renegades
email: Renegades@domain.com
description: Climb Ride Cuddle
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://cshell7.github.io/renegades/"

# Build settings
markdown: kramdown
